stages:
  - linting
  - testing


flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose --import-order-style=google

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --config .black .

test:
  stage: testing
  image: python:3.10
  script:
    - pip install -r requirements/test.txt
    - cd lyceum
    - python manage.py test
