# Generated by Django 4.2.5 on 2023-11-10 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "created_on",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("processing", "В обработке"),
                            ("answered", "Ответ дан"),
                        ],
                        default="received",
                        max_length=11,
                        verbose_name="статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "обратная связь",
                "verbose_name_plural": "обратные связи",
            },
        ),
        migrations.CreateModel(
            name="StatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="время"),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("processing", "В обработке"),
                            ("answered", "Ответ дан"),
                        ],
                        db_column="from",
                        max_length=11,
                        verbose_name="из",
                    ),
                ),
                (
                    "to",
                    models.CharField(
                        choices=[
                            ("received", "Получено"),
                            ("processing", "В обработке"),
                            ("answered", "Ответ дан"),
                        ],
                        max_length=11,
                        verbose_name="в",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                        verbose_name="фидбек",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "лог",
                "verbose_name_plural": "логи",
            },
        ),
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, verbose_name="имя")),
                ("mail", models.EmailField(max_length=254, verbose_name="почта")),
                (
                    "feedback",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedback.feedback",
                        verbose_name="фидбек",
                    ),
                ),
            ],
            options={
                "verbose_name": "персональные данные",
                "verbose_name_plural": "персональные данные",
            },
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=feedback.models.FileUpload._feedback_upload_path,
                        verbose_name="файлы",
                    ),
                ),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to="feedback.feedback",
                        verbose_name="фидбек",
                    ),
                ),
            ],
            options={
                "verbose_name": "файл",
                "verbose_name_plural": "файлы",
            },
        ),
    ]
