# Generated by Django 4.2.5 on 2023-10-26 15:41

import catalog.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимум 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Максимальная длина - 200 символов, уникальное значение рамках таблицы, только цифры, буквы латиницы и символы `-` и `_`",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Za-z0-9\\-_]+$")
                        ],
                        verbose_name="слаг",
                    ),
                ),
                (
                    "normalization",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        unique=True,
                        verbose_name="нормализированное имя",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32767),
                        ],
                        verbose_name="Вес",
                    ),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимум 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Добавьте краткое описание товара используя слова `превосходно` или `роскошно`",
                        validators=[
                            catalog.validators.ValidateMustContain(
                                "превосходно", "роскошно"
                            )
                        ],
                        verbose_name="Описание",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.CreateModel(
            name="MainImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длина названия - 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="main_images", verbose_name="изображение"
                    ),
                ),
            ],
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимум 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="опубликовано"),
                ),
                (
                    "slug",
                    models.CharField(
                        help_text="Максимальная длина - 200 символов, уникальное значение рамках таблицы, только цифры, буквы латиницы и символы `-` и `_`",
                        max_length=200,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^[A-Za-z0-9\\-_]+$")
                        ],
                        verbose_name="слаг",
                    ),
                ),
                (
                    "normalization",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        unique=True,
                        verbose_name="нормализированное имя",
                    ),
                ),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="ManyImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Максимальная длина названия - 150 символов",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="extra_images", verbose_name="изображение"
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="catalog.item"
                    ),
                ),
            ],
            options={
                "verbose_name": "изображение",
                "verbose_name_plural": "изображения",
            },
        ),
        migrations.AddField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                help_text="Выберите главное изображение товара",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="catalog.mainimagemodel",
                verbose_name="главное изображение",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="tags",
            field=models.ManyToManyField(
                help_text="Выберите теги, описывающие данный товар.",
                related_name="items",
                to="catalog.tag",
            ),
        ),
    ]
