# Generated by Django 4.2.5 on 2023-10-26 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_postironia"),
    ]

    operations = [
        migrations.DeleteModel(
            name="postironia",
        ),
    ]
