# Generated by Django 4.2.5 on 2023-10-26 20:43

import catalog.validators
import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_delete_postironia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor.fields.RichTextField(
                help_text="Добавьте краткое описание товара используя слова `превосходно` или `роскошно`",
                validators=[
                    catalog.validators.ValidateMustContain("превосходно", "роскошно")
                ],
                verbose_name="Описание",
            ),
        ),
    ]
