# Generated by Django 4.2.5 on 2023-11-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0007_alter_category_normalization_alter_item_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="дата создания"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                help_text="Максимальная длина - 200 символов, уникальное значение рамках таблицы, только цифры, буквы латиницы и символы `-` и `_`",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                help_text="Максимальная длина - 200 символов, уникальное значение рамках таблицы, только цифры, буквы латиницы и символы `-` и `_`",
                max_length=200,
                unique=True,
                verbose_name="слаг",
            ),
        ),
    ]
